---

name: "Basics of Github Actions"

on:
  push:
    branches:
      - master
      - testing

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: "running date command"
        run: date
        shell: bash

      - name: "OS details"
        run: cat /etc/os-release
        shell: bash

      - name: "user details"
        run: whoami
        shell: bash

      - name: "curent working directory before checkout"
        run: |
          pwd 
          ls -al

      - name: "checkout repository"
        uses: actions/checkout@v3

      - name: "curent working directory after checkout"
        run: |
          pwd
          ls -al

      - name: "download and installing terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

      - name: "terraform version"
        run: terraform version      

      - name: "running script.sh"
        run: |
          chmod +x script.sh
          ./script.sh    
